# importing numpy and panda

In [6]:
import pandas as pd

In [7]:
import numpy as np

In [8]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [9]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0                 30          0         2    1                          4  
1                 31          0         1    0                          0  
2                 31          0         0    0                          2  
3                 24          0         2    0                          4  
4                 30          0         2    1                          2  
..               ...        ...       ...  ...                        ...  
695               22          1         2    0                          8  
696               24          0         1    2                          3  
697               25          1         0    0                          8  
698               25          1         0    0                          2  
699               25          0         1    1                          2  

[700 rows x 15 columns]

In [10]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [11]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
5           0         0         0         1           10                2   
6           0         0         0         1            7                4   
7           0         0         0         1            7                4   
8           0         0         1         0            6                6   
9           0         0         0         1            7                0   
10          1         0         0         0            7                0   
11          1         0         0         0            7                1   
12          1         0         0         0            7                2   
13          1         0         0         0            7                2   
14          0         0         0         1            7                2   
15          1         0         0         0            7                4   
16          0         0         0         1            7                4   
17          0         0         1         0            7                0   
18          1         0         0         0            7                3   
19          0         0         0         1            5                4   
20          1         0         0         0           12                1   
21          1         0         0         0            3                6   
22          1         0         0         0           10                3   
23          0         0         0         1            8                4   
24          0         0         1         0            8                0   
25          0         0         0         1            8                0   
26          0         0         0         1            4                2   
27          0         0         0         1           12                1   
28          0         0         1         0            8                2   
29          0         0         0         1            8                4   
30          0         0         1         0            8                0   
31          0         0         1         0            8                3   
32          0         0         0         1            8                3   
33          0         0         1         0            8                0   
34          0         0         0         1            8                0   
35          0         0         0         1            8                0   
36          0         0         0         1            4                2   
37          1         0         0         0            8                3   
38          0         0         0         1            8                4   
39          0         0         0         1            8                4   
40          0         0         0         1            1                4   
41          0         0         0         1            7                3   
42          0         0         0         1            1                4   
43          0         0         1         0            8                6   
44          0         0         0         1            9                2   
45          0         0         0         1            9                6   
46          0         0         0         1            9                0   
47          0         0         0         1            9                3   
48          0         0         0         1            4                3   
49          1         0         0         0            9                0   
50          0         0         0         0            9                0   
5

In [12]:
target = np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)
data_preprocessed['Excessive Absenteeism'] = target
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
5           0         0         0         1           10                2   
6           0         0         0         1            7                4   
7           0         0         0         1            7                4   
8           0         0         1         0            6                6   
9           0         0         0         1            7                0   
10          1         0         0         0            7                0   
11          1         0         0         0            7                1   
12          1         0         0         0            7                2   
13          1         0         0         0            7                2   
14          0         0         0         1            7                2   
15          1         0         0         0            7                4   
16          0         0         0         1            7                4   
17          0         0         1         0            7                0   
18          1         0         0         0            7                3   
19          0         0         0         1            5                4   
20          1         0         0         0           12                1   
21          1         0         0         0            3                6   
22          1         0         0         0           10                3   
23          0         0         0         1            8                4   
24          0         0         1         0            8                0   
25          0         0         0         1            8                0   
26          0         0         0         1            4                2   
27          0         0         0         1           12                1   
28          0         0         1         0            8                2   
29          0         0         0         1            8                4   
30          0         0         1         0            8                0   
31          0         0         1         0            8                3   
32          0         0         0         1            8                3   
33          0         0         1         0            8                0   
34          0         0         0         1            8                0   
35          0         0         0         1            8                0   
36          0         0         0         1            4                2   
37          1         0         0         0            8                3   
38          0         0         0         1            8                4   
39          0         0         0         1            8                4   
40          0         0         0         1            1                4   
41          0         0         0         1            7                3   
42          0         0         0         1            1                4   
43          0         0         1         0            8                6   
44          0         0         0         1            9                2   
45          0         0         0         1            9                6   
46          0         0         0         1            9                0   
47          0         0         0         1            9                3   
48          0         0         0         1            4                3   
49          1         0         0         0            9                0   
50          0         0         0         0            9                0   
5

In [13]:
target.sum()/target.shape[0]

0.45571428571428574

In [73]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Day of the Week', 'Distance to Work',
        'Daily Work Load Average'],axis =1)
data_with_targets

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
5           0         0         0         1           10   
6           0         0         0         1            7   
7           0         0         0         1            7   
8           0         0         1         0            6   
9           0         0         0         1            7   
10          1         0         0         0            7   
11          1         0         0         0            7   
12          1         0         0         0            7   
13          1         0         0         0            7   
14          0         0         0         1            7   
15          1         0         0         0            7   
16          0         0         0         1            7   
17          0         0         1         0            7   
18          1         0         0         0            7   
19          0         0         0         1            5   
20          1         0         0         0           12   
21          1         0         0         0            3   
22          1         0         0         0           10   
23          0         0         0         1            8   
24          0         0         1         0            8   
25          0         0         0         1            8   
26          0         0         0         1            4   
27          0         0         0         1           12   
28          0         0         1         0            8   
29          0         0         0         1            8   
30          0         0         1         0            8   
31          0         0         1         0            8   
32          0         0         0         1            8   
33          0         0         1         0            8   
34          0         0         0         1            8   
35          0         0         0         1            8   
36          0         0         0         1            4   
37          1         0         0         0            8   
38          0         0         0         1            8   
39          0         0         0         1            8   
40          0         0         0         1            1   
41          0         0         0         1            7   
42          0         0         0         1            1   
43          0         0         1         0            8   
44          0         0         0         1            9   
45          0         0         0         1            9   
46          0         0         0         1            9   
47          0         0         0         1            9   
48          0         0         0         1            4   
49          1         0         0         0            9   
50          0         0         0         0            9   
51          0         0         0         0            9   
52          0         0         0         1            8   
53          0         0         0         1            9   
54          0         0         0         0            9   
55          0         0         0         0            9   
56          0         0         1         0            9   
57          0         0         0         1            9   
58          0         0         0         0            9   
59          0         0         0         1           11   
60          0         0         0         1            9   
61          0         0         0         1            9   
62          0         0         0         1            6   
63          0         0         0         1           10   
64          0         0         0         0           10   
65          0         0         0         1  

In [74]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
5           0         0         0         1           10   
6           0         0         0         1            7   
7           0         0         0         1            7   
8           0         0         1         0            6   
9           0         0         0         1            7   
10          1         0         0         0            7   
11          1         0         0         0            7   
12          1         0         0         0            7   
13          1         0         0         0            7   
14          0         0         0         1            7   
15          1         0         0         0            7   
16          0         0         0         1            7   
17          0         0         1         0            7   
18          1         0         0         0            7   
19          0         0         0         1            5   
20          1         0         0         0           12   
21          1         0         0         0            3   
22          1         0         0         0           10   
23          0         0         0         1            8   
24          0         0         1         0            8   
25          0         0         0         1            8   
26          0         0         0         1            4   
27          0         0         0         1           12   
28          0         0         1         0            8   
29          0         0         0         1            8   
30          0         0         1         0            8   
31          0         0         1         0            8   
32          0         0         0         1            8   
33          0         0         1         0            8   
34          0         0         0         1            8   
35          0         0         0         1            8   
36          0         0         0         1            4   
37          1         0         0         0            8   
38          0         0         0         1            8   
39          0         0         0         1            8   
40          0         0         0         1            1   
41          0         0         0         1            7   
42          0         0         0         1            1   
43          0         0         1         0            8   
44          0         0         0         1            9   
45          0         0         0         1            9   
46          0         0         0         1            9   
47          0         0         0         1            9   
48          0         0         0         1            4   
49          1         0         0         0            9   
50          0         0         0         0            9   
51          0         0         0         0            9   
52          0         0         0         1            8   
53          0         0         0         1            9   
54          0         0         0         0            9   
55          0         0         0         0            9   
56          0         0         1         0            9   
57          0         0         0         1            9   
58          0         0         0         0            9   
59          0         0         0         1           11   
60          0         0         0         1            9   
61          0         0         0         1            9   
62          0         0         0         1            6   
63          0         0         0         1           10   
64          0         0         0         0           10   
65          0         0         0         1  

In [101]:
unscaled_inputs = data_with_targets.iloc[:,:-1]
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
5           0         0         0         1           10   
6           0         0         0         1            7   
7           0         0         0         1            7   
8           0         0         1         0            6   
9           0         0         0         1            7   
10          1         0         0         0            7   
11          1         0         0         0            7   
12          1         0         0         0            7   
13          1         0         0         0            7   
14          0         0         0         1            7   
15          1         0         0         0            7   
16          0         0         0         1            7   
17          0         0         1         0            7   
18          1         0         0         0            7   
19          0         0         0         1            5   
20          1         0         0         0           12   
21          1         0         0         0            3   
22          1         0         0         0           10   
23          0         0         0         1            8   
24          0         0         1         0            8   
25          0         0         0         1            8   
26          0         0         0         1            4   
27          0         0         0         1           12   
28          0         0         1         0            8   
29          0         0         0         1            8   
30          0         0         1         0            8   
31          0         0         1         0            8   
32          0         0         0         1            8   
33          0         0         1         0            8   
34          0         0         0         1            8   
35          0         0         0         1            8   
36          0         0         0         1            4   
37          1         0         0         0            8   
38          0         0         0         1            8   
39          0         0         0         1            8   
40          0         0         0         1            1   
41          0         0         0         1            7   
42          0         0         0         1            1   
43          0         0         1         0            8   
44          0         0         0         1            9   
45          0         0         0         1            9   
46          0         0         0         1            9   
47          0         0         0         1            9   
48          0         0         0         1            4   
49          1         0         0         0            9   
50          0         0         0         0            9   
51          0         0         0         0            9   
52          0         0         0         1            8   
53          0         0         0         1            9   
54          0         0         0         0            9   
55          0         0         0         0            9   
56          0         0         1         0            9   
57          0         0         0         1            9   
58          0         0         0         0            9   
59          0         0         0         1           11   
60          0         0         0         1            9   
61          0         0         0         1            9   
62          0         0         0         1            6   
63          0         0         0         1           10   
64          0         0         0         0           10   
65          0         0         0         1  

# Standardize the data

In [76]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler = StandardScaler()

In [102]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [103]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [104]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

# split the data in train and test then shuffle

In [105]:
from sklearn.model_selection import train_test_split

In [106]:
train_test_split(scaled_inputs,target)

[array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297],
        [-0.57735027, -0.09298136,  3.17979734, ..., -0.44798003,
         -0.01928035,  2.8430157 ],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  0.26848661],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        ...,
        [ 1.73205081, -0.09298136, -0.31448545, ..., -

In [109]:
x_train,x_test,y_train,y_test  = train_test_split(scaled_inputs, target, train_size = 0.8)

In [110]:
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(560, 11) (560,)
(140, 11) (140,)


# Logistic Regression with sklearn

In [111]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics


In [112]:
reg = LogisticRegression()
reg.fit(x_train,y_train)

LogisticRegression()

In [113]:
reg.score(x_train,y_train)

0.775

## Manually checking accuracy

In [114]:
model_outputs = reg.predict(x_train)
model_outputs

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,

In [115]:
y_train

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,

In [116]:
model_outputs==y_train

array([False,  True,  True,  True,  True,  True, False,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False, False,  True,
       False,  True, False, False,  True,  True, False,  True, False,
       False,  True, False, False,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [117]:
np.sum(model_outputs==y_train)

434

In [118]:
model_outputs.shape[0]

560

In [119]:
np.sum(model_outputs==y_train)/model_outputs.shape[0]

0.775

## Finding intercepts and coefficients

In [120]:
reg.intercept_

array([-0.25119611])

In [121]:
reg.coef_

array([[ 2.0789062 ,  0.39113306,  1.53105802,  1.3707799 , -0.02857308,
         0.72252598, -0.24443266,  0.30524038,  0.03840067,  0.46165255,
        -0.39068566]])

In [122]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [123]:
feature_name = unscaled_inputs.columns.values

In [124]:
summary_table = pd.DataFrame(columns = ['Features'],data = feature_name)
summary_table['Coefficient' ] = np.transpose(reg.coef_)
summary_table.index = summary_table.index+1
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table


Features  Coefficient
0                Intercept    -0.251196
1                 Reason_1     2.078906
2                 Reason_2     0.391133
3                 Reason_3     1.531058
4                 Reason_4     1.370780
5              Month Value    -0.028573
6   Transportation Expense     0.722526
7                      Age    -0.244433
8          Body Mass Index     0.305240
9                Education     0.038401
10                Children     0.461653
11                     Pet    -0.390686

## Interpreting the coefficients 

In [125]:
summary_table['Odds_Ratio']= np.exp(summary_table.Coefficient)

In [126]:
summary_table

Features  Coefficient  Odds_Ratio
0                Intercept    -0.251196    0.777870
1                 Reason_1     2.078906    7.995718
2                 Reason_2     0.391133    1.478655
3                 Reason_3     1.531058    4.623066
4                 Reason_4     1.370780    3.938421
5              Month Value    -0.028573    0.971831
6   Transportation Expense     0.722526    2.059629
7                      Age    -0.244433    0.783149
8          Body Mass Index     0.305240    1.356951
9                Education     0.038401    1.039148
10                Children     0.461653    1.586694
11                     Pet    -0.390686    0.676593

In [127]:
summary_table.sort_values('Odds_Ratio',ascending = False)
summary_table

Features  Coefficient  Odds_Ratio
0                Intercept    -0.251196    0.777870
1                 Reason_1     2.078906    7.995718
2                 Reason_2     0.391133    1.478655
3                 Reason_3     1.531058    4.623066
4                 Reason_4     1.370780    3.938421
5              Month Value    -0.028573    0.971831
6   Transportation Expense     0.722526    2.059629
7                      Age    -0.244433    0.783149
8          Body Mass Index     0.305240    1.356951
9                Education     0.038401    1.039148
10                Children     0.461653    1.586694
11                     Pet    -0.390686    0.676593

# testing the model

In [128]:
reg.score(x_test,y_test)

0.7642857142857142

In [129]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.85107438, 0.14892562],
       [0.89410408, 0.10589592],
       [0.1271249 , 0.8728751 ],
       [0.68889411, 0.31110589],
       [0.12430416, 0.87569584],
       [0.32704604, 0.67295396],
       [0.79008507, 0.20991493],
       [0.5722557 , 0.4277443 ],
       [0.5722557 , 0.4277443 ],
       [0.32516599, 0.67483401],
       [0.77850895, 0.22149105],
       [0.53826276, 0.46173724],
       [0.37002265, 0.62997735],
       [0.61781229, 0.38218771],
       [0.77703028, 0.22296972],
       [0.48647079, 0.51352921],
       [0.41367385, 0.58632615],
       [0.78290279, 0.21709721],
       [0.95444376, 0.04555624],
       [0.84668481, 0.15331519],
       [0.88829878, 0.11170122],
       [0.7681974 , 0.2318026 ],
       [0.93886021, 0.06113979],
       [0.77554458, 0.22445542],
       [0.75261549, 0.24738451],
       [0.75261549, 0.24738451],
       [0.89730068, 0.10269932],
       [0.7681974 , 0.2318026 ],
       [0.17061673, 0.82938327],
       [0.52974755, 0.47025245],
       [0.

In [133]:
predicted_proba[:,1]

array([0.14892562, 0.10589592, 0.8728751 , 0.31110589, 0.87569584,
       0.67295396, 0.20991493, 0.4277443 , 0.4277443 , 0.67483401,
       0.22149105, 0.46173724, 0.62997735, 0.38218771, 0.22296972,
       0.51352921, 0.58632615, 0.21709721, 0.04555624, 0.15331519,
       0.11170122, 0.2318026 , 0.06113979, 0.22445542, 0.24738451,
       0.24738451, 0.10269932, 0.2318026 , 0.82938327, 0.47025245,
       0.67714013, 0.43403788, 0.237952  , 0.81761555, 0.27924556,
       0.21855479, 0.68237377, 0.80618576, 0.67714013, 0.91565111,
       0.27410941, 0.14676998, 0.51196917, 0.31282536, 0.67303127,
       0.93913747, 0.45748768, 0.50925396, 0.237952  , 0.18520015,
       0.24106846, 0.1042868 , 0.37815592, 0.12272415, 0.1511073 ,
       0.10835062, 0.03373549, 0.50983145, 0.73736954, 0.15220796,
       0.86176139, 0.66961402, 0.14784455, 0.12364818, 0.67714013,
       0.58677184, 0.95491335, 0.76048269, 0.95600551, 0.24579514,
       0.68521917, 0.2113373 , 0.72730883, 0.10589592, 0.86446

# save the model

import pickle

In [135]:
import pickle
with open('model','wb') as file:
    
     pickle.dump(reg,file)

In [136]:

with open('scaler','wb') as file:
    
     pickle.dump(absenteeism_scaler,file)